using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Stalker_EN.Camera;

/// <summary>
/// Minimal borderless window for displaying a captured photograph.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STPhotoWindow : BaseWindow
{
    private static readonly TimeSpan LoadingTimeout = TimeSpan.FromSeconds(5);

    private float _loadingElapsed;
    private bool _isLoading;

    public STPhotoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
    }

    /// <summary>
    /// Display the photo texture and hide the loading label.
    /// </summary>
    public void SetTexture(Texture texture)
    {
        _isLoading = false;
        PhotoTexture.Texture = texture;
        LoadingLabel.Visible = false;
    }

    /// <summary>
    /// Begin loading state, starting the timeout timer.
    /// </summary>
    public void StartLoading()
    {
        _isLoading = true;
        _loadingElapsed = 0f;
        LoadingLabel.Text = Loc.GetString("st-photo-loading");
        LoadingLabel.Visible = true;
        PhotoTexture.Texture = null;
    }

    /// <summary>
    /// Show "Photo unavailable" when the photo cannot be loaded.
    /// </summary>
    public void ShowUnavailable()
    {
        _isLoading = false;
        LoadingLabel.Text = Loc.GetString("st-photo-unavailable");
        LoadingLabel.Visible = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isLoading)
            return;

        _loadingElapsed += args.DeltaSeconds;

        if (_loadingElapsed >= LoadingTimeout.TotalSeconds)
            ShowUnavailable();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
