- type: entity
  id: STBaseTeleport
  abstract: true
  suffix: Teleport, Portal
  components:
  - type: Marker
  - type: Transform
    anchored: True
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      portalFixture:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - TableLayer
        hard: false
  - type: InteractionOutline
  - type: Clickable
  - type: STAnomalyGeneratorSpawnBlocker
    size: 5
  # ST14-EN: This intentionally doesn't have emission lightning blocker

- type: entity
  parent: STBaseTeleport
  id: MapTeleportBase
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: portal-red
    sprite: /Textures/Effects/portal.rsi
  # stalker-en-changes
  - type: Portal
  - type: LinkByString
  # stalker-en-changes
  - type: PointLight
    color: Yellow
    radius: 3
    energy: 1
    netsync: false

- type: entity
  parent: STBaseTeleport
  id: MapTeleportBaseUncollide
  abstract: true
  components:
  - type: Sprite  # I think you'll need to add an invisibility here
    layers:
    - state: portal-red
    sprite: /Textures/Effects/portal.rsi
  # stalker-en-changes
  - type: Portal
  - type: LinkByString
  # stalker-en-changes-end
  - type: PointLight
    color: OrangeRed
    radius: 3
    energy: 1
    netsync: false

- type: entity
  parent: STBaseTeleport
  id: LocalTeleportBase
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: portal-red
    sprite: /Textures/Effects/portal.rsi
  # stalker-en-changes
  - type: Portal
  - type: LinkByString
  # stalker-en-changes-end

- type: entity
  parent: STBaseTeleport
  id: LocalTeleportBaseUncollide
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: portal-red
    sprite: /Textures/Effects/portal.rsi
  # stalker-en-changes
  - type: Portal
  - type: LinkByString
  # stalker-en-changes-end

# Portal system template
- type: entity
  parent:
  - STBaseTeleport
  - MapTeleportBase
  id: TemplateTeleport
  abstract: true
  name: TestMapTeleport
  components:
  - type: Portal
