using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.StalkerRepository;

[GenerateTypedNameReferences]
public sealed partial class ItemCategory : PanelContainer
{
    public ItemCategory(string category)
    {
        RobustXamlLoader.Load(this);

        CategoryLabel.Text = $"[bold][color=orange]{category.ToUpper()}[/color][/bold]";
    }
}
