- type: job
  id: StalkerClearSky
  name: job-clearsky
  icon: cn
  description: job-clearsky-desc
  playTimeTracker: JobClearSky
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobClearSky
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerClearSkyGear
  supervisors: job-clearsky-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - CN
      - type: Bands
        altBand: stalker
        canChange: true
        band: Stalker
        bandIcon: cn
        bandProto: STClearSkyBand
        bandRankId: 1
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: NpcFactionMember
        factions:
        - ClearSky
      - type: Vocal # stalker EN change start
        sounds:
          Male: MaleHumanLoner
          Female: FemaleHumanLoner
          Unsexed: MaleHumanLoner # stalker EN change end

- type: job
  id: StalkerHeadClearSky
  name: job-clearsky-commander
  icon: cn
  description: job-clearsky-commander-desc
  playTimeTracker: JobHeadClearSky
  whitelisted: true
  requirements:
  # - !type:RoleTimeRequirement
  #   role: JobClearSky
  #   time: 1
  - !type:SpeciesRequirement
    species:
    - Human
    - Dwarf
  startingGear: StalkerClearSkyGearHead # EN
  supervisors: job-clearsky-commander-supervisor
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
    - type: Access
      tags:
      - CN
    - type: Bands
      altBand: stalker
      canChange: true
      band: Stalker
      bandIcon: cn
      bandProto: STClearSkyBand
      bandRankId: 2
    - type: BlockTackingHolyItems
    - type: TeethPull
      teethProto: ToothStalker
      pullingItemTag: PliersStalker
      teethCount: 3
      initialTeeth: 3
    - type: NpcFactionMember
      factions:
      - ClearSky
    - type: Vocal # stalker EN change start
      sounds:
        Male: MaleHumanLoner
        Female: FemaleHumanLoner
        Unsexed: MaleHumanLoner # stalker EN change end

- type: startingGear
  id: StalkerClearSkyGear
  equipment:
    id: ClearSkyPDA
    dogtag: ClothingNeckDogtagClearSky

- type: startingGear
  id: StalkerClearSkyGearHead
  equipment:
    id: ClearSkyPDA
    dogtag: ClothingNeckDogtagClearSkyLeader

- type: stBand
  id: STClearSkyBand
  name: Clear Sky
  factionId: ClearSky
  maxMembers: 11
  managingRankId: 2
  hierarchy:
    1: StalkerClearSky
    2: StalkerHeadClearSky
