- type: job
  id: StalkerMercenary
  name: job-mercenary
  icon: merc
  description: job-mercenary-desc
  playTimeTracker: JobStalkerMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerMercenaryGear
  supervisors: job-mercenary-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
          bandProto: STMercenariesBand
          bandRankId: 1
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3
        - type: Vocal # stalker EN change start
          sounds:
            Male: MaleHumanMerc
            Female: FemaleHumanMerc
            Unsexed: MaleHumanMerc # stalker EN change end

- type: startingGear
  id: StalkerMercenaryGear
  equipment:
    id: MercPDA
    dogtag: ClothingNeckDogtagMercenary # EN
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: StalkerHeadMercenary
  name: job-head-mercenary
  icon: merc
  description: job-head-mercenary-desc
  playTimeTracker: JobStalkerHeadMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerHeadMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerHeadMercenaryGear
  supervisors: job-head-mercenary-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadMerc
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
          bandProto: STMercenariesBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3
        - type: Vocal # stalker EN change start
          sounds:
            Male: MaleHumanMerc
            Female: FemaleHumanMerc
            Unsexed: MaleHumanMerc # stalker EN change end

- type: startingGear
  id: StalkerHeadMercenaryGear
  equipment:
    id: MercPDA
    dogtag: ClothingNeckDogtagMercenaryCommander # EN
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
    back: ClothingBackpackDuffelBlackStalker
- type: stBand
  id: STMercenariesBand
  name: Mercenaries
  factionId: Mercenaries
  maxMembers: 11
  managingRankId: 2
  hierarchy:
    1: StalkerMercenary
    2: StalkerHeadMercenary
